### ISSUE TITLE
仓库地址 https 证书问题

### ISSUE THREAD

**Issue by arstercz** [dromara/Jpom#32]
在增加仓库的时候, 比如 gitlab 地址含有自签的证书, jpom 会出现以下错误:
```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at sun.security.validator.Validator.validate(Validator.java:271)
```

能否增加选项关闭 ssl 验证, 类似 git 的配置:
```
git config --global http.sslVerify false
```

**Comment by bwcx-jzy** [comment]
感谢反馈，2.10.12 默认忽略ssl验证
