### ISSUE TITLE
控制台一直提示：会话已经关闭[project-console]

### ISSUE THREAD

**Issue by wujiops** [dromara/Jpom#97]
![image](https://github.com/user-attachments/assets/2deb5fe0-9d8d-44a7-9a3c-8865af1ecf75)
服务端报错：
2024-10-28 13:31:14.280 [http-nio-2122-exec-2] WARN  o.d.j.s.ServerWebSocketInterceptor [ServerWebSocketInterceptor.java:110] - 传入的类型错误：null
Agent端报错：
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0xff0xf40xff0xfd0x06...]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.lang.Thread.run(Thread.java:750)
这个该怎样解决？jdk21，昨天可以用，今天就不行了，修改了配置文件功能都正常，今天就不行了，就对配置做了回滚，jdk也降级到jdk8了，但是这个问题还是出现，已经尝试了更换nginx服务器(推荐配置)，重启服务，都不行。也检查了防火墙都是通的。

**Comment by bwcx-jzy** [comment]
使用的官方包吗？没有进行二开过？

**Comment by wujiops** [comment]
找到原因了，设置了BASE64，改成NONE就行了，nginx-1.26.2版本。
# 前端消息传输需要编码或者加密 目前支持：NONE、BASE64
transport-encryption: NONE
